config/routes.rb
Rails.application.routes.draw do
  resources :listing_posts

end

app/models/listing_post.rb
class ListingPost < ActiveRecord::Base
	has_attached_file :image, styles: {large: "600x600>",medium: "300x300>", thumb: "150x150#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listing_posts_controller.rb
class ListingPostsController < ApplicationController
  before_action :set_listing_post, only: [:show, :edit, :update, :destroy]

  # GET /listing_posts
  # GET /listing_posts.json
  def index
    @listing_posts = ListingPost.all
  end

  # GET /listing_posts/1
  # GET /listing_posts/1.json
  def show
  end

  # GET /listing_posts/new
  def new
    @listing_post = ListingPost.new
  end

  # GET /listing_posts/1/edit
  def edit
  end

  # POST /listing_posts
  # POST /listing_posts.json
  def create
    @listing_post = ListingPost.new(listing_post_params)

    respond_to do |format|
      if @listing_post.save
        format.html { redirect_to @listing_post, notice: 'Listing post was successfully created.' }
        format.json { render :show, status: :created, location: @listing_post }
      else
        format.html { render :new }
        format.json { render json: @listing_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listing_posts/1
  # PATCH/PUT /listing_posts/1.json
  def update
    respond_to do |format|
      if @listing_post.update(listing_post_params)
        format.html { redirect_to @listing_post, notice: 'Listing post was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing_post }
      else
        format.html { render :edit }
        format.json { render json: @listing_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listing_posts/1
  # DELETE /listing_posts/1.json
  def destroy
    @listing_post.destroy
    respond_to do |format|
      format.html { redirect_to listing_posts_url, notice: 'Listing post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing_post
      @listing_post = ListingPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_post_params
      params.require(:listing_post).permit(:Title, :Content,:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listing_posts_helper.rb
module ListingPostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageUpload</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/listing_posts/_form.html.erb
<%= form_for @listing_post, html: { multipart: true } do |f| %>
  <% if @listing_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing_post.errors.count, "error") %> prohibited this listing_post from being saved:</h2>

      <ul>
      <% @listing_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>


  <div class="field">
    <%= f.label :Title %><br>
    <%= f.text_field :Title %>
  </div>
  <div class="field">
    <%= f.label :Content %><br>
    <%= f.text_field :Content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listing_posts/edit.html.erb
<h1>Editing Listing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing_post %> |
<%= link_to 'Back', listing_posts_path %>

app/views/listing_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listing_posts.each do |listing_post| %>
      <tr>
        <td><%= listing_post.Title %></td>
        <td><%= listing_post.Content %></td>
        <td><%= image_tag listing_post.image.url(:thumb)%></td>
        <td><%= link_to 'Show', listing_post %></td>
        <td><%= link_to 'Edit', edit_listing_post_path(listing_post) %></td>
        <td><%= link_to 'Destroy', listing_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing post', new_listing_post_path %>

app/views/listing_posts/new.html.erb
<h1>New Listing Post</h1>

<%= render 'form' %>

<%= link_to 'Back', listing_posts_path %>

app/views/listing_posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @listing_post.image.url(:large)%>

<p>
  <strong>Title:</strong>
  <%= @listing_post.Title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @listing_post.Content %>
</p>

<%= link_to 'Edit', edit_listing_post_path(@listing_post) %> |
<%= link_to 'Back', listing_posts_path %>